version: '3.4'

services:
  cma.ismai.trello.api:
    image: ${DOCKER_REGISTRY-}cmaismaitrelloapi
    build:
      context: .
      dockerfile: CMA.ISMAI.Trello.API/Dockerfile

  cma.ismai.sagas.ui:
    image: ${DOCKER_REGISTRY-}cmaismaisagasui
    build:
      context: .
      dockerfile: CMA.ISMAI.Sagas/Dockerfile


  cma.ismai.notifications:
    image: ${DOCKER_REGISTRY-}cmaismainotifications
    build:
      context: .
      dockerfile: CMA.ISMAI.Notifications/Dockerfile


  cma.ismai.solutions.creditacoes.ui:
    image: ${DOCKER_REGISTRY-}cmaismaisolutionscreditacoesui
    build:
      context: .
      dockerfile: CMA.ISMAI.Solutions.Creditacoes.UI/Dockerfile

